/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gomoku;

/**
 *
 * @author kito
 */
public class menu3 extends javax.swing.JFrame {

    private Game myGame;
            
    public menu3() {
        initComponents();
    }
    
    public void setGame(Game s){
        myGame = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nxt = new javax.swing.JLabel();
        hardC = new javax.swing.JLabel();
        meduim = new javax.swing.JLabel();
        hard = new javax.swing.JLabel();
        easy = new javax.swing.JLabel();
        medC = new javax.swing.JLabel();
        easyC = new javax.swing.JLabel();
        white = new javax.swing.JLabel();
        black = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gomoku - Single Player");
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        nxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/nxt.png"))); // NOI18N
        nxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nxtMouseClicked(evt);
            }
        });
        getContentPane().add(nxt);
        nxt.setBounds(540, 390, 70, 50);

        hardC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/hardw.PNG"))); // NOI18N
        hardC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardCMouseClicked(evt);
            }
        });
        getContentPane().add(hardC);
        hardC.setBounds(80, 370, 100, 40);

        meduim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/meduim.PNG"))); // NOI18N
        getContentPane().add(meduim);
        meduim.setBounds(80, 240, 90, 100);

        hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/hard.PNG"))); // NOI18N
        getContentPane().add(hard);
        hard.setBounds(200, 320, 100, 100);

        easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/easy.PNG"))); // NOI18N
        getContentPane().add(easy);
        easy.setBounds(210, 170, 90, 70);

        medC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/med.PNG"))); // NOI18N
        medC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medCMouseClicked(evt);
            }
        });
        getContentPane().add(medC);
        medC.setBounds(160, 270, 130, 40);

        easyC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/easyw.PNG"))); // NOI18N
        easyC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyCMouseClicked(evt);
            }
        });
        getContentPane().add(easyC);
        easyC.setBounds(90, 190, 100, 40);

        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/white.PNG"))); // NOI18N
        white.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteMouseClicked(evt);
            }
        });
        getContentPane().add(white);
        white.setBounds(440, 180, 50, 60);

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/black.PNG"))); // NOI18N
        black.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackMouseClicked(evt);
            }
        });
        getContentPane().add(black);
        black.setBounds(440, 260, 50, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/back3.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 640, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxtMouseClicked
        setVisible(false);
        board a = new board();
        a.setGame(myGame);
        a.setVisible(true);
    }//GEN-LAST:event_nxtMouseClicked

    private void easyCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyCMouseClicked
        myGame.levelOfDiff = 1;
        medC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/med.PNG")));
        easyC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/easychoosen.PNG")));
        hardC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/hardw.PNG")));
    }//GEN-LAST:event_easyCMouseClicked

    private void medCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medCMouseClicked
        myGame.levelOfDiff = 2;
        medC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/medchoosen.PNG")));
        easyC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/easyw.PNG")));
        hardC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/hardw.PNG")));
    }//GEN-LAST:event_medCMouseClicked

    private void hardCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardCMouseClicked
        myGame.levelOfDiff = 3;
        medC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/med.PNG")));
        easyC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/easyw.PNG")));
        hardC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/hardchoosen.PNG")));
    }//GEN-LAST:event_hardCMouseClicked

    private void whiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteMouseClicked
        myGame.p1.setColor(1); //set color white
        myGame.p1.setPriorty(2); // set priorty second
        
        myGame.p2.setColor(2);  //set color black
        myGame.p2.setPriorty(1); // set priorty first
        
        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/whitechoosen.PNG")));
        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/black.PNG")));
    }//GEN-LAST:event_whiteMouseClicked

    private void blackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackMouseClicked
        myGame.p1.setColor(2);  //set color black
        myGame.p1.setPriorty(1); // set priorty first
        
        myGame.p2.setColor(1); // set color white
        myGame.p2.setPriorty(2); // set priorty second
        
        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/blackchoosen.PNG")));
        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gomoku/white.PNG")));
    }//GEN-LAST:event_blackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel black;
    private javax.swing.JLabel easy;
    private javax.swing.JLabel easyC;
    private javax.swing.JLabel hard;
    private javax.swing.JLabel hardC;
    private javax.swing.JLabel medC;
    private javax.swing.JLabel meduim;
    private javax.swing.JLabel nxt;
    private javax.swing.JLabel white;
    // End of variables declaration//GEN-END:variables
}
